In [3]:
from tkinter import *
master = Tk()

def var_states():
    import pandas as pd
    import numpy
    def show_entry_fields():
        print("Enemy  Number: %s: " % (e1.get()))
        usr_id_no=int(e1.get())
        import pandas as pd
        import numpy
        column_names2 = ['user_id', 'Toy_Story', 'GoldenEye', 'FourRooms','GetShorty','Copycat'] 
        df1 = pd.read_csv("Book1.csv", sep=',', names=column_names) 
        
        print(df.iloc[usr_id_no:usr_id_no+1]) 

  
# Print the dataframe 
    import pandas as pd 
    column_names = ['user_id', 'Toy_Story', 'GoldenEye', 'FourRooms','GetShorty','Copycat'] 
    df = pd.read_csv("Book1.csv", sep=',', names=column_names) 
    
    
   #print("male: %d,\nfemale: %d" % (var1.get(), var2.get()))
    if var1.get()!=1:
        v1=0
    else:
        v1=1
    if var2.get()!=1:
        v2=0
    else:
        v2=1
    if var3.get()!=1:
        v3=0
    else:
        v3=1
    if var4.get()!=1:
        v4=0
    else:
        v4=1
    if var5.get()!=1:
        v5=0
    else:
        v5=1
    k=[]
    k.append(v1)
    k.append(v2)
    k.append(v3)
    k.append(v4)
    k.append(v5)


    print(k)
    
    compare_list=[]
# Iterate over each row 
    for index, rows in df.iterrows(): 
        # Create list for the current row 
        my_list =[ rows.Toy_Story, rows.GoldenEye,rows.FourRooms,rows.GetShorty,rows.Copycat]
        #print(my_list)
        import numpy as np
        val=np.logical_xor(k,my_list )
        print(val)
        bool_val = numpy.multiply(val, 1) 
        print(bool_val)
        ones=np.count_nonzero(bool_val)
        print(ones)

        compare_list.append(ones)
    print(compare_list)
    result = numpy.where(compare_list== numpy.amax(compare_list))
    print(result[0])
    as_1=result[0]
    print(as_1)
    for x in range(len(as_1)):
        print("Your enemy is",as_1[x])
    #import random

    #least_user_val= random.choice(as_1)
    #print(least_user_val)
    
    #df.iloc[least_user_val]
    #print("Your enemy is user",least_user_val)
    for x in range(len(as_1)):
        s=8+x
        lsum = Label(master, text = 'Your enemy is:',width="115",font=("Helvetica", 16))
        lsum.grid(row=s, sticky=W, pady=4)
        lsum["text"] = "Your enemy is user number : " + str(as_1[x])
        
    Label(master, text="Enter the enenmy user_id from above options",width="115",font=("Helvetica", 16)).grid(row=s+2)

    e1 = Entry(master)

    e1.grid(row=s+3)
    Button(master, text='OK', command=show_entry_fields,width="200",bg="green").grid(row=s+4, sticky=W,pady=4)
    
    


        

Label(master, text="Select your movie:",font=("Helvetica", 16),width="115").grid(row=0, sticky=W)

var1 = IntVar()
Checkbutton(master, text="Toy Story (1995)", variable=var1,width="115",font=("Helvetica", 16)).grid(row=1, sticky=W)

var2 = IntVar()
Checkbutton(master, text="GoldenEye (1995)", variable=var2,width="115",font=("Helvetica", 16)).grid(row=2, sticky=W)

var3 = IntVar()
Checkbutton(master, text="Four Rooms (1995)", variable=var3,width="115",font=("Helvetica", 16)).grid(row=3, sticky=W)

var4 = IntVar()
Checkbutton(master, text="Get Shorty (1995)", variable=var4,width="115",font=("Helvetica", 16)).grid(row=4, sticky=W)

var5 = IntVar()
Checkbutton(master, text="Copycat (1995)", variable=var5,width="115",font=("Helvetica", 16)).grid(row=5, sticky=W)





#Button(master, text='Quit', command=master.quit).grid(row=6, sticky=W, pady=4)
Button(master, text='Show', command=var_states,width="200",bg="green").grid(row=7, sticky=W, pady=4)


mainloop()

[0, 0, 0, 0, 1]
[False  True  True False  True]
[0 1 1 0 1]
3
[False False  True False  True]
[0 0 1 0 1]
2
[ True  True  True  True False]
[1 1 1 1 0]
4
[False False False False False]
[0 0 0 0 0]
0
[ True False  True False False]
[1 0 1 0 0]
2
[3, 2, 4, 0, 2]
[2]
[2]
Your enemy is 2
Enemy  Number: 2: 
  user_id  Toy_Story  GoldenEye  FourRooms  GetShorty  Copycat
2  user_3          1          1          1          1        1


In [2]:
import pandas as pd
import numpy
  
# Create the dataframe 
#df = pd.DataFrame({'Date':['10/2/2011', '11/2/2011', '12/2/2011', '13/2/11'], 
                    #'Event':['Music', 'Poetry', 'Theatre', 'Comedy'], 
                    #'Cost':[10000, 5000, 15000, 2000]}) 
  
# Print the dataframe 
import pandas as pd 
column_names = ['user_id', 'Toy_Story', 'GoldenEye', 'FourRooms','GetShorty','Copycat'] 
df = pd.read_csv("Book1.csv", sep=',', names=column_names) 
#print(df) 

k=[0, 1, 1, 0, 0]
compare_list=[]
# Iterate over each row 
for index, rows in df.iterrows(): 
    # Create list for the current row 
    my_list =[ rows.Toy_Story, rows.GoldenEye,rows.FourRooms,rows.GetShorty,rows.Copycat]
    #print(my_list)
    import numpy as np
    val=np.logical_xor(k,my_list )
    print(val)
    bool_val = numpy.multiply(val, 1) 
    print(bool_val)
    ones=np.count_nonzero(bool_val)
    print(ones)
    
    compare_list.append(ones)
   
  
# Print the list 
print(compare_list)
result = numpy.where(compare_list== numpy.amax(compare_list))
print(result[0])
as_1=result[0]
print(as_1)

[False False False False False]
[0 0 0 0 0]
0
[False  True False False False]
[0 1 0 0 0]
1
[ True False False  True  True]
[1 0 0 1 1]
3
[False  True  True False  True]
[0 1 1 0 1]
3
[ True  True False False  True]
[1 1 0 0 1]
3
[0, 1, 3, 3, 3]
[2 3 4]
[2 3 4]


In [126]:
import random

least_user_val= random.choice(as_1)
print(least_user_val)

3


In [127]:
df.iloc[least_user_val]

user_id      user_4
Toy_Story         0
GoldenEye         0
FourRooms         0
GetShorty         0
Copycat           1
Name: 3, dtype: object

In [39]:
for x in range(len(as_1)): 
    print (""as_1[x]) 

2
3
4


In [16]:
import pandas as pd
import numpy
column_names = ['user_id', 'Toy_Story', 'GoldenEye', 'FourRooms','GetShorty','Copycat'] 
df3 = pd.read_csv("Book1.csv", sep=',', names=column_names) 

In [23]:
df3.iloc[4:5] 

user_id  Toy_Story  GoldenEye  FourRooms  GetShorty  Copycat
4  user_5          1          0          1          0        1

In [24]:
k=[]
k=df3.iloc[4:5]

In [25]:
print (k)

  user_id  Toy_Story  GoldenEye  FourRooms  GetShorty  Copycat
4  user_5          1          0          1          0        1


In [26]:
for index, rows in k.iterrows(): 
    # Create list for the current row 
    my_list4 =[ rows.Toy_Story, rows.GoldenEye,rows.FourRooms,rows.GetShorty,rows.Copycat]


In [27]:
print(my_list4)

[1, 0, 1, 0, 1]


In [89]:
print(val45)

[False  True False  True False]


In [94]:
bool_val45 = numpy.multiply(val45, 1) 


In [95]:
print(bool_val45)

[0 1 0 1 0]


[0 1 0 1 0]


In [99]:
list1 = [i^1 for i in bool_val45] 


In [100]:
print(list1)

[1, 0, 1, 0, 1]


In [6]:
def get_my_friend():
    k=e1.get()
    print(k)

In [7]:
get_my_friend()

NameError: name 'e1' is not defined