In [2]:
from tkinter import *
from functools import partial

master = Tk()

def var_states():
    import pandas as pd
    import numpy
   
    def popupmsg(msg):
        import tkinter as tk
        from tkinter import ttk
        LARGE_FONT= ("Verdana", 12)
        NORM_FONT = ("Helvetica", 10)
        SMALL_FONT = ("Helvetica", 8)
        popup = tk.Tk()
        popup.wm_title("!")
        label = ttk.Label(popup, text=msg, font=LARGE_FONT)
        label.pack(side="bottom", fill="x", pady=10)
        B1 = ttk.Button(popup, text="Okay", command = popup.destroy)
        B1.pack()
        popup.mainloop()
    
    def show_entry_fields(as_1):
        check_val=0
        print("as_1 sec",as_1)
        u_val=int(e1.get())
        if u_val in as_1:
            check_val=1

        else:
            check_val=0
        if(check_val==0):
            print("wrong option")
            popupmsg("wrong opton")
            
        if (check_val==1):
        
            compare_list_2=[]
            print("Enemy  Number: %s: " % (e1.get()))
            usr_id_no=int(e1.get())
            import pandas as pd
            import numpy
            column_names2 = ['user_id', 'Toy_Story', 'GoldenEye', 'FourRooms','GetShorty','Copycat'] 
            df1 = pd.read_csv("Book1.csv", sep=',', names=column_names) 

            #getting friend from enemy

            print(df1.iloc[usr_id_no:usr_id_no+1]) 
            k1=[]
            k1=df1.iloc[usr_id_no:usr_id_no+1]
            #print(k1)
            for index, rows in k1.iterrows():
                # Create list for the current row 
                my_list_enemy=[ rows.Toy_Story, rows.GoldenEye,rows.FourRooms,rows.GetShorty,rows.Copycat]
            #print(my_list_enemy)

            for index, rows in df1.iterrows(): 
            # Create list for the current row 
                my_list_1 =[ rows.Toy_Story, rows.GoldenEye,rows.FourRooms,rows.GetShorty,rows.Copycat]
                #print(my_list)
                import numpy as np
                val_new=np.logical_xor(my_list_enemy,my_list_1 )
                print(val_new)
                bool_val_2 = numpy.multiply(val_new, 1) 
                print(bool_val_2)


                ones_2=np.count_nonzero(bool_val_2)
                print(ones_2)
                compare_list_2.append(ones_2)
            print("comapre list is:",compare_list_2)
            result_2 = numpy.where(compare_list_2==numpy.amax(compare_list_2))
            print(result_2[0])
            as_12=result_2[0]
            print(as_12)
            for x in range(len(as_12)):
                print("Your Friend is",as_12[x])
            for x in range(len(as_12)):
                s=13+x
                lsum_2 = Label(master, text = 'Your Friend is:',width="115",font=("Helvetica", 16))
                lsum_2.grid(row=s, sticky=W, pady=4)
                lsum_2["text"] = "Your Friend is user number : " + str(as_12[x])

            
        
  
# Print the dataframe 
    import pandas as pd 
    column_names = ['user_id', 'Toy_Story', 'GoldenEye', 'FourRooms','GetShorty','Copycat'] 
    df = pd.read_csv("Book1.csv", sep=',', names=column_names) 
    
    
   #print("male: %d,\nfemale: %d" % (var1.get(), var2.get()))
    if var1.get()!=1:
        v1=0
    else:
        v1=1
    if var2.get()!=1:
        v2=0
    else:
        v2=1
    if var3.get()!=1:
        v3=0
    else:
        v3=1
    if var4.get()!=1:
        v4=0
    else:
        v4=1
    if var5.get()!=1:
        v5=0
    else:
        v5=1
    k=[]
    k.append(v1)
    k.append(v2)
    k.append(v3)
    k.append(v4)
    k.append(v5)


    print(k)
    
    compare_list=[]
# Iterate over each row 
    for index, rows in df.iterrows(): 
        # Create list for the current row 
        my_list =[ rows.Toy_Story, rows.GoldenEye,rows.FourRooms,rows.GetShorty,rows.Copycat]
        #print(my_list)
        import numpy as np
        val=np.logical_xor(k,my_list )
        print(val)
        bool_val = numpy.multiply(val, 1) 
        print(bool_val)
        ones=np.count_nonzero(bool_val)
        print(ones)

        compare_list.append(ones)
    print(compare_list)
    result = numpy.where(compare_list== numpy.amax(compare_list))
    print(result[0])
    as_1=result[0]
    print("as_1 first",as_1)
    for x in range(len(as_1)):
        print("Your enemy is here ",as_1[x])
    #import random

    #least_user_val= random.choice(as_1)
    #print(least_user_val)
    
    #df.iloc[least_user_val]
    #print("Your enemy is user",least_user_val)
    for x in range(len(as_1)):
        s=8+x
        lsum = Label(master, text = 'Your enemy is:',width="115",font=("Helvetica", 16))
        lsum.grid(row=s, sticky=W, pady=4)
        lsum["text"] = "Your enemy is user number : " + str(as_1[x])
        
    Label(master, text="Enter the enenmy user_id from above options",width="115",font=("Helvetica", 16)).grid(row=s+2)

    e1 = Entry(master)
    e1.grid(row=s+3)
    #Button(master, text='OK', command=show_entry_fields,width="200",bg="green").grid(row=s+4, sticky=W,pady=4)
    Button(master, text='OK', command=partial(show_entry_fields, as_1),width="200",bg="green").grid(row=s+4, sticky=W,pady=4)


    

    
            
    
  


        

Label(master, text="Select your movie:",font=("Helvetica", 16),width="115").grid(row=0, sticky=W)

var1 = IntVar()
Checkbutton(master, text="Toy Story (1995)", variable=var1,width="115",font=("Helvetica", 16)).grid(row=1, sticky=W)

var2 = IntVar()
Checkbutton(master, text="GoldenEye (1995)", variable=var2,width="115",font=("Helvetica", 16)).grid(row=2, sticky=W)

var3 = IntVar()
Checkbutton(master, text="Four Rooms (1995)", variable=var3,width="115",font=("Helvetica", 16)).grid(row=3, sticky=W)

var4 = IntVar()
Checkbutton(master, text="Get Shorty (1995)", variable=var4,width="115",font=("Helvetica", 16)).grid(row=4, sticky=W)

var5 = IntVar()
Checkbutton(master, text="Copycat (1995)", variable=var5,width="115",font=("Helvetica", 16)).grid(row=5, sticky=W)





#Button(master, text='Quit', command=master.quit).grid(row=6, sticky=W, pady=4)
Button(master, text='Show', command=var_states,width="200",bg="green").grid(row=7, sticky=W, pady=4)


mainloop()

[1, 1, 0, 0, 0]
[ True False  True False False]
[1 0 1 0 0]
2
[ True  True  True False False]
[1 1 1 0 0]
3
[False False  True  True  True]
[0 0 1 1 1]
3
[ True  True False False  True]
[1 1 0 0 1]
3
[False  True  True False  True]
[0 1 1 0 1]
3
[2, 3, 3, 3, 3]
[1 2 3 4]
as_1 first [1 2 3 4]
Your enemy is here  1
Your enemy is here  2
Your enemy is here  3
Your enemy is here  4
as_1 sec [1 2 3 4]
Enemy  Number: 3: 
  user_id  Toy_Story  GoldenEye  FourRooms  GetShorty  Copycat
3  user_4          0          0          0          0        1
[False  True  True False  True]
[0 1 1 0 1]
3
[False False  True False  True]
[0 0 1 0 1]
2
[ True  True  True  True False]
[1 1 1 1 0]
4
[False False False False False]
[0 0 0 0 0]
0
[ True False  True False False]
[1 0 1 0 0]
2
comapre list is: [3, 2, 4, 0, 2]
[2]
[2]
Your Friend is 2
as_1 sec [1 2 3 4]
Enemy  Number: 3: 
  user_id  Toy_Story  GoldenEye  FourRooms  GetShorty  Copycat
3  user_4          0          0          0          0        1
[Fa